[package]
name = "linera-ethereum"
description = "Oracle functionality for Ethereum"
readme = "README.md"
documentation = "https://docs.rs/linera-ethereum/latest/linera_ethereum/"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
features = ["ethereum"]

[features]
ethereum = []

[dependencies]
anyhow.workspace = true
ethers.workspace = true
ethers-core.workspace = true
ethers-middleware.workspace = true
ethers-providers.workspace = true
ethers-signers.workspace = true
linera-storage-service.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
rustc-hex.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
url.workspace = true

[build-dependencies]
cfg_aliases.workspace = true
