name: Benchmarks

on:
  push:
    branches: [ main, 'devnet_*', 'testnet_*' ]
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - 'CONTRIBUTING.md'
      - 'INSTALL.md'
      - 'docker/**'
      - 'docker_scylla/**'
      - 'configuration/**'
      - 'kubernetes/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10

jobs:
  benchmark:
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run benchmarks
      run: |
        cargo bench -p linera-service
